import { MenuItem, Order, User, OrderStatus, CartItem, Notification } from './types';

// Mock data - 50+ menu items with proper categorization
const menuItems: MenuItem[] = [
  // South Indian Breakfast (10 items)
  {
    id: '1',
    name: 'Masala Dosa',
    description: 'Crispy rice crepe with spiced potato filling, served with sambar and chutneys',
    price: 60,
    category: 'breakfast',
    cuisine: 'south-indian',
    mealTime: 'breakfast',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400',
    available: true,
    preparationTime: 15,
    isVeg: true,
  },
  {
    id: '2',
    name: 'Idli Sambar',
    description: 'Steamed rice cakes with lentil soup and coconut chutney',
    price: 40,
    category: 'breakfast',
    cuisine: 'south-indian',
    mealTime: 'breakfast',
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=400',
    available: true,
    preparationTime: 10,
    isVeg: true,
  },
  {
    id: '3',
    name: 'Medu Vada',
    description: 'Crispy lentil donuts served with sambar and chutney',
    price: 45,
    category: 'breakfast',
    cuisine: 'south-indian',
    mealTime: 'breakfast',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    available: true,
    preparationTime: 12,
    isVeg: true,
  },
  {
    id: '4',
    name: 'Pongal',
    description: 'Rice and lentil porridge tempered with cumin and pepper',
    price: 50,
    category: 'breakfast',
    cuisine: 'south-indian',
    mealTime: 'breakfast',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400',
    available: true,
    preparationTime: 15,
    isVeg: true,
  },
  {
    id: '5',
    name: 'Uttapam',
    description: 'Thick rice pancake topped with onions, tomatoes, and chilies',
    price: 55,
    category: 'breakfast',
    cuisine: 'south-indian',
    mealTime: 'breakfast',
    image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=400',
    available: true,
    preparationTime: 12,
    isVeg: true,
  },
  {
    id: '6',
    name: 'Rava Dosa',
    description: 'Crispy semolina crepe with onions and spices',
    price: 65,
    category: 'breakfast',
    cuisine: 'south-indian',
    mealTime: 'breakfast',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400',
    available: true,
    preparationTime: 15,
    isVeg: true,
  },
  {
    id: '7',
    name: 'Upma',
    description: 'Savory semolina porridge with vegetables and spices',
    price: 35,
    category: 'breakfast',
    cuisine: 'south-indian',
    mealTime: 'breakfast',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400',
    available: true,
    preparationTime: 10,
    isVeg: true,
  },
  {
    id: '8',
    name: 'Pesarattu',
    description: 'Green gram dosa served with ginger chutney',
    price: 55,
    category: 'breakfast',
    cuisine: 'south-indian',
    mealTime: 'breakfast',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400',
    available: true,
    preparationTime: 15,
    isVeg: true,
  },
  {
    id: '9',
    name: 'Appam with Stew',
    description: 'Soft rice pancakes with coconut milk vegetable stew',
    price: 70,
    category: 'breakfast',
    cuisine: 'south-indian',
    mealTime: 'breakfast',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400',
    available: true,
    preparationTime: 18,
    isVeg: true,
  },
  {
    id: '10',
    name: 'Poori Masala',
    description: 'Fried bread with spiced potato curry',
    price: 50,
    category: 'breakfast',
    cuisine: 'south-indian',
    mealTime: 'breakfast',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    available: true,
    preparationTime: 15,
    isVeg: true,
  },

  // North Indian Main Course (12 items)
  {
    id: '11',
    name: 'Paneer Butter Masala',
    description: 'Cottage cheese in rich creamy tomato gravy',
    price: 140,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
    available: true,
    preparationTime: 20,
    isVeg: true,
  },
  {
    id: '12',
    name: 'Dal Makhani',
    description: 'Creamy black lentils slow-cooked with butter and cream',
    price: 120,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
    available: true,
    preparationTime: 25,
    isVeg: true,
  },
  {
    id: '13',
    name: 'Chole Bhature',
    description: 'Spicy chickpea curry with fried bread',
    price: 90,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'breakfast',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=400',
    available: true,
    preparationTime: 20,
    isVeg: true,
    isSpicy: true,
  },
  {
    id: '14',
    name: 'Rajma Chawal',
    description: 'Red kidney beans curry with steamed rice',
    price: 100,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'lunch',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2fb3f1?w=400',
    available: true,
    preparationTime: 15,
    isVeg: true,
  },
  {
    id: '15',
    name: 'Kadai Paneer',
    description: 'Cottage cheese cooked with bell peppers and spices',
    price: 150,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
    available: true,
    preparationTime: 22,
    isVeg: true,
    isSpicy: true,
  },
  {
    id: '16',
    name: 'Aloo Gobi',
    description: 'Potato and cauliflower cooked with spices',
    price: 110,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400',
    available: true,
    preparationTime: 18,
    isVeg: true,
  },
  {
    id: '17',
    name: 'Palak Paneer',
    description: 'Cottage cheese in spinach gravy',
    price: 135,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
    available: true,
    preparationTime: 20,
    isVeg: true,
  },
  {
    id: '18',
    name: 'Butter Chicken',
    description: 'Tender chicken in creamy tomato butter sauce',
    price: 180,
    category: 'dinner',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2fb3f1?w=400',
    available: true,
    preparationTime: 25,
    isVeg: false,
  },
  {
    id: '19',
    name: 'Chicken Tikka Masala',
    description: 'Grilled chicken pieces in spicy tomato gravy',
    price: 190,
    category: 'dinner',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2fb3f1?w=400',
    available: true,
    preparationTime: 28,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '20',
    name: 'North Indian Thali',
    description: 'Complete meal with dal, sabzi, roti, rice, raita, and salad',
    price: 160,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'lunch',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2fb3f1?w=400',
    available: true,
    preparationTime: 20,
    isVeg: true,
  },
  {
    id: '21',
    name: 'Naan with Dal Makhani',
    description: 'Butter naan served with creamy black lentils',
    price: 130,
    category: 'dinner',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
    available: true,
    preparationTime: 22,
    isVeg: true,
  },
  {
    id: '22',
    name: 'Sarson Ka Saag with Makki Roti',
    description: 'Mustard greens curry with cornmeal flatbread',
    price: 145,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'lunch',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2fb3f1?w=400',
    available: true,
    preparationTime: 25,
    isVeg: true,
  },

  // Chettinad Cuisine (8 items)
  {
    id: '23',
    name: 'Chettinad Chicken Curry',
    description: 'Spicy chicken curry with roasted spices and coconut',
    price: 170,
    category: 'lunch',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2fb3f1?w=400',
    available: true,
    preparationTime: 30,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '24',
    name: 'Chettinad Fish Fry',
    description: 'Spicy marinated fish fry with South Indian spices',
    price: 200,
    category: 'dinner',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1580959375944-c1be5e2b0835?w=400',
    available: true,
    preparationTime: 25,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '25',
    name: 'Chettinad Mushroom Masala',
    description: 'Button mushrooms in spicy Chettinad gravy',
    price: 140,
    category: 'lunch',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400',
    available: true,
    preparationTime: 22,
    isVeg: true,
    isSpicy: true,
  },
  {
    id: '26',
    name: 'Chettinad Egg Curry',
    description: 'Boiled eggs in spicy coconut-based gravy',
    price: 120,
    category: 'lunch',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2fb3f1?w=400',
    available: true,
    preparationTime: 20,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '27',
    name: 'Chettinad Veg Kurma',
    description: 'Mixed vegetables in aromatic Chettinad coconut gravy',
    price: 130,
    category: 'lunch',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400',
    available: true,
    preparationTime: 20,
    isVeg: true,
    isSpicy: true,
  },
  {
    id: '28',
    name: 'Chettinad Biryani',
    description: 'Fragrant rice with Chettinad spices and vegetables',
    price: 160,
    category: 'dinner',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    available: true,
    preparationTime: 35,
    isVeg: true,
    isSpicy: true,
  },
  {
    id: '29',
    name: 'Mutton Chettinad',
    description: 'Tender mutton in traditional Chettinad spice blend',
    price: 220,
    category: 'dinner',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2fb3f1?w=400',
    available: true,
    preparationTime: 40,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '30',
    name: 'Chettinad Potato Roast',
    description: 'Spicy roasted potatoes with curry leaves',
    price: 100,
    category: 'lunch',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400',
    available: true,
    preparationTime: 15,
    isVeg: true,
    isSpicy: true,
  },

  // South Indian Rice & Biryani (5 items)
  {
    id: '31',
    name: 'Vegetable Biryani',
    description: 'Fragrant basmati rice with mixed vegetables and spices',
    price: 140,
    category: 'lunch',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
    available: true,
    preparationTime: 30,
    isVeg: true,
  },
  {
    id: '32',
    name: 'Chicken Biryani',
    description: 'Aromatic rice with tender chicken pieces and spices',
    price: 180,
    category: 'dinner',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/appetizing-chicken-biryani-in-a-traditio-f03ca459-20251109055152.jpg',
    available: true,
    preparationTime: 35,
    isVeg: false,
  },
  {
    id: '33',
    name: 'Lemon Rice',
    description: 'Tangy rice seasoned with lemon and peanuts',
    price: 80,
    category: 'lunch',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2fb3f1?w=400',
    available: true,
    preparationTime: 12,
    isVeg: true,
  },
  {
    id: '34',
    name: 'Curd Rice',
    description: 'Cooling rice mixed with yogurt and tempered spices',
    price: 70,
    category: 'lunch',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2fb3f1?w=400',
    available: true,
    preparationTime: 10,
    isVeg: true,
  },
  {
    id: '35',
    name: 'Sambar Rice',
    description: 'Rice mixed with flavorful lentil and vegetable stew',
    price: 90,
    category: 'lunch',
    cuisine: 'south-indian',
    mealTime: 'lunch',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2fb3f1?w=400',
    available: true,
    preparationTime: 15,
    isVeg: true,
  },

  // Non-Veg Dishes (30 items)
  {
    id: '76',
    name: 'Mutton Biryani',
    description: 'Slow-cooked tender mutton with aromatic basmati rice and spices',
    price: 220,
    category: 'dinner',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/delicious-mutton-biryani-served-in-an-or-2d33a81f-20251109055152.jpg',
    available: true,
    preparationTime: 40,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '77',
    name: 'Fish Curry',
    description: 'Fresh fish cooked in traditional South Indian curry with coconut',
    price: 160,
    category: 'lunch',
    cuisine: 'south-indian',
    mealTime: 'lunch',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/south-indian-fish-curry-in-a-clay-pot-fr-2d986b83-20251109055151.jpg',
    available: true,
    preparationTime: 25,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '78',
    name: 'Chicken Fried Rice',
    description: 'Wok-tossed rice with chicken, vegetables and soy sauce',
    price: 150,
    category: 'dinner',
    cuisine: 'chinese',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chinese-chicken-fried-rice-on-a-white-pl-5786a631-20251109055152.jpg',
    available: true,
    preparationTime: 20,
    isVeg: false,
  },
  {
    id: '79',
    name: 'Chicken Noodles',
    description: 'Stir-fried noodles with chicken and mixed vegetables',
    price: 140,
    category: 'dinner',
    cuisine: 'chinese',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chicken-hakka-noodles-on-a-black-plate-s-84444c74-20251109055152.jpg',
    available: true,
    preparationTime: 18,
    isVeg: false,
  },
  {
    id: '80',
    name: 'Chicken 65',
    description: 'Spicy deep-fried chicken marinated with South Indian spices',
    price: 170,
    category: 'snacks',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chicken-65-on-a-banana-leaf-crispy-deep--80e43af1-20251109055153.jpg',
    available: true,
    preparationTime: 20,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '81',
    name: 'Kola Urundai (Meatballs)',
    description: 'Spiced minced meat balls deep-fried to perfection',
    price: 180,
    category: 'snacks',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/kola-urundai-chettinad-meatballs-on-a-tr-5fb4499e-20251109055152.jpg',
    available: true,
    preparationTime: 25,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '82',
    name: 'Chicken Tikka',
    description: 'Grilled chicken chunks marinated in yogurt and spices',
    price: 190,
    category: 'dinner',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chicken-tikka-on-skewers-grilled-marinat-ce1941b3-20251109055152.jpg',
    available: true,
    preparationTime: 25,
    isVeg: false,
  },
  {
    id: '83',
    name: 'Mutton Curry',
    description: 'Tender mutton cooked in rich, spicy gravy',
    price: 210,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'lunch',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/mutton-curry-in-a-copper-serving-bowl-te-f4229d70-20251109055152.jpg',
    available: true,
    preparationTime: 35,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '84',
    name: 'Chicken Curry',
    description: 'Classic chicken curry with aromatic spices',
    price: 160,
    category: 'lunch',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/south-indian-chicken-curry-in-a-traditio-4cd90368-20251109055153.jpg',
    available: true,
    preparationTime: 25,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '85',
    name: 'Fish Fry',
    description: 'Crispy pan-fried fish with South Indian masala',
    price: 180,
    category: 'dinner',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/fish-fry-on-a-white-plate-crispy-pan-fri-dda5950b-20251109055152.jpg',
    available: true,
    preparationTime: 20,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '86',
    name: 'Prawn Masala',
    description: 'Juicy prawns cooked in spicy tomato-based gravy',
    price: 220,
    category: 'dinner',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/prawn-masala-in-a-black-bowl-large-juicy-cb2d4f20-20251109055151.jpg',
    available: true,
    preparationTime: 25,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '87',
    name: 'Mutton Rogan Josh',
    description: 'Kashmiri-style aromatic mutton curry',
    price: 230,
    category: 'dinner',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/mutton-rogan-josh-in-an-ornate-serving-d-3085de4e-20251109055152.jpg',
    available: true,
    preparationTime: 40,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '88',
    name: 'Chicken Kolhapuri',
    description: 'Spicy chicken curry from Kolhapur region',
    price: 175,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chicken-kolhapuri-on-a-traditional-thali-8e571d4b-20251109055153.jpg',
    available: true,
    preparationTime: 28,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '89',
    name: 'Chicken Manchurian',
    description: 'Indo-Chinese chicken balls in tangy sauce',
    price: 160,
    category: 'snacks',
    cuisine: 'chinese',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chicken-manchurian-on-a-white-plate-cris-6c049628-20251109055151.jpg',
    available: true,
    preparationTime: 22,
    isVeg: false,
  },
  {
    id: '90',
    name: 'Chilli Chicken',
    description: 'Spicy chicken stir-fry with bell peppers and sauces',
    price: 170,
    category: 'snacks',
    cuisine: 'chinese',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chilli-chicken-on-a-black-plate-stir-fri-f68a164b-20251109055152.jpg',
    available: true,
    preparationTime: 20,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '91',
    name: 'Chicken Lollipop',
    description: 'Crispy fried chicken wings shaped like lollipops',
    price: 180,
    category: 'snacks',
    cuisine: 'chinese',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chicken-lollipop-appetizer-on-a-serving--1fb3c0c5-20251109055151.jpg',
    available: true,
    preparationTime: 22,
    isVeg: false,
  },
  {
    id: '92',
    name: 'Tandoori Chicken',
    description: 'Chicken marinated in yogurt and spices, grilled in tandoor',
    price: 200,
    category: 'dinner',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/tandoori-chicken-on-a-sizzling-platter-h-3c75728c-20251109055152.jpg',
    available: true,
    preparationTime: 30,
    isVeg: false,
  },
  {
    id: '93',
    name: 'Egg Biryani',
    description: 'Fragrant rice with boiled eggs and aromatic spices',
    price: 130,
    category: 'lunch',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/egg-biryani-in-a-traditional-handi-pot-f-1c7dfe44-20251109055152.jpg',
    available: true,
    preparationTime: 25,
    isVeg: false,
  },
  {
    id: '94',
    name: 'Chicken Kebab',
    description: 'Minced chicken skewers with herbs and spices',
    price: 185,
    category: 'snacks',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chicken-kebab-skewers-on-a-wooden-board--5ba5d210-20251109055152.jpg',
    available: true,
    preparationTime: 25,
    isVeg: false,
  },
  {
    id: '95',
    name: 'Mutton Keema',
    description: 'Minced mutton cooked with peas and spices',
    price: 195,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'lunch',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/mutton-keema-in-a-copper-bowl-minced-mut-470b82f3-20251109055148.jpg',
    available: true,
    preparationTime: 30,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '96',
    name: 'Chicken Korma',
    description: 'Mild chicken curry with yogurt and cashew gravy',
    price: 175,
    category: 'lunch',
    cuisine: 'north-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chicken-korma-in-an-elegant-serving-bowl-9a0761c3-20251109055151.jpg',
    available: true,
    preparationTime: 25,
    isVeg: false,
  },
  {
    id: '97',
    name: 'Prawn Biryani',
    description: 'Aromatic rice with succulent prawns',
    price: 240,
    category: 'dinner',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/prawn-biryani-in-a-decorative-bowl-aroma-e9d6f352-20251109055154.jpg',
    available: true,
    preparationTime: 35,
    isVeg: false,
  },
  {
    id: '98',
    name: 'Fish Biryani',
    description: 'Fragrant rice with marinated fish pieces',
    price: 190,
    category: 'dinner',
    cuisine: 'south-indian',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/fish-biryani-served-in-a-traditional-ves-057bdd28-20251109055152.jpg',
    available: true,
    preparationTime: 30,
    isVeg: false,
  },
  {
    id: '99',
    name: 'Pepper Chicken',
    description: 'Spicy chicken fry with crushed black pepper',
    price: 170,
    category: 'snacks',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/pepper-chicken-on-a-banana-leaf-dry-frie-8288d0cc-20251109055152.jpg',
    available: true,
    preparationTime: 20,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '100',
    name: 'Chicken Chukka',
    description: 'Dry spicy chicken fry from Chettinad cuisine',
    price: 180,
    category: 'snacks',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chicken-chukka-on-a-traditional-plate-dr-1a1c61a5-20251109055154.jpg',
    available: true,
    preparationTime: 25,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '101',
    name: 'Mutton Chukka',
    description: 'Dry spicy mutton fry with roasted spices',
    price: 210,
    category: 'snacks',
    cuisine: 'chettinad',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/mutton-chukka-on-a-clay-plate-dry-roaste-73ca5d0c-20251109055152.jpg',
    available: true,
    preparationTime: 35,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '102',
    name: 'Chicken Schezwan',
    description: 'Spicy chicken in Schezwan sauce with vegetables',
    price: 165,
    category: 'dinner',
    cuisine: 'chinese',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/chicken-schezwan-on-a-white-plate-spicy--f61253e0-20251109055152.jpg',
    available: true,
    preparationTime: 20,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '103',
    name: 'Egg Fried Rice',
    description: 'Fried rice with scrambled eggs and vegetables',
    price: 110,
    category: 'dinner',
    cuisine: 'chinese',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
    available: true,
    preparationTime: 15,
    isVeg: false,
  },
  {
    id: '104',
    name: 'Chicken Wings',
    description: 'Crispy fried chicken wings with hot sauce',
    price: 190,
    category: 'snacks',
    cuisine: 'continental',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/crispy-chicken-wings-on-a-wooden-board-g-48467a77-20251109055152.jpg',
    available: true,
    preparationTime: 22,
    isVeg: false,
    isSpicy: true,
  },
  {
    id: '105',
    name: 'Grilled Chicken',
    description: 'Marinated chicken breast grilled to perfection',
    price: 200,
    category: 'dinner',
    cuisine: 'continental',
    mealTime: 'all-day',
    image: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/d75fdac5-8e8c-4740-82f7-9a7c6ce5d262/generated_images/grilled-chicken-breast-on-a-white-plate--6ebc9c11-20251109055151.jpg',
    available: true,
    preparationTime: 25,
    isVeg: false,
  },

  // Snacks (20+ items)
  {
    id: '36',
    name: 'Samosa',
    description: 'Crispy fried pastry with spiced potato filling',
    price: 20,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '37',
    name: 'Pav Bhaji',
    description: 'Spiced vegetable mash served with buttered bread',
    price: 80,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    available: true,
    preparationTime: 15,
    isVeg: true,
  },
  {
    id: '38',
    name: 'Vada Pav',
    description: 'Spiced potato fritter in a bread bun',
    price: 30,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    available: true,
    preparationTime: 8,
    isVeg: true,
  },
  {
    id: '39',
    name: 'Bread Pakora',
    description: 'Bread slices dipped in gram flour batter and deep-fried',
    price: 35,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    available: true,
    preparationTime: 10,
    isVeg: true,
  },
  {
    id: '40',
    name: 'Aloo Tikki',
    description: 'Spiced potato patties, crispy outside and soft inside',
    price: 40,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    available: true,
    preparationTime: 12,
    isVeg: true,
  },
  {
    id: '41',
    name: 'Paneer Pakora',
    description: 'Cottage cheese fritters with spices',
    price: 60,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    available: true,
    preparationTime: 12,
    isVeg: true,
  },
  {
    id: '42',
    name: 'Onion Bhaji',
    description: 'Crispy onion fritters with gram flour',
    price: 45,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    available: true,
    preparationTime: 10,
    isVeg: true,
  },
  {
    id: '43',
    name: 'Mirchi Bajji',
    description: 'Stuffed chili fritters in spiced batter',
    price: 35,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    available: true,
    preparationTime: 10,
    isVeg: true,
    isSpicy: true,
  },
  {
    id: '44',
    name: 'Spring Roll',
    description: 'Crispy rolls filled with vegetables',
    price: 50,
    category: 'snacks',
    cuisine: 'chinese',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400',
    available: true,
    preparationTime: 12,
    isVeg: true,
  },
  {
    id: '45',
    name: 'Veg Cutlet',
    description: 'Mixed vegetable patties, breaded and fried',
    price: 40,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    available: true,
    preparationTime: 10,
    isVeg: true,
  },
  {
    id: '46',
    name: 'French Fries',
    description: 'Crispy fried potato fingers',
    price: 50,
    category: 'snacks',
    cuisine: 'continental',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
    available: true,
    preparationTime: 8,
    isVeg: true,
  },
  {
    id: '47',
    name: 'Corn Sandwich',
    description: 'Grilled sandwich with spiced corn filling',
    price: 55,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400',
    available: true,
    preparationTime: 10,
    isVeg: true,
  },
  {
    id: '48',
    name: 'Cheese Sandwich',
    description: 'Toasted sandwich with cheese and vegetables',
    price: 60,
    category: 'snacks',
    cuisine: 'continental',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400',
    available: true,
    preparationTime: 8,
    isVeg: true,
  },
  {
    id: '49',
    name: 'Masala Puri',
    description: 'Crispy puris topped with spiced chickpeas',
    price: 45,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    available: true,
    preparationTime: 10,
    isVeg: true,
    isSpicy: true,
  },
  {
    id: '50',
    name: 'Bhel Puri',
    description: 'Puffed rice snack with vegetables and tangy chutneys',
    price: 40,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '51',
    name: 'Papdi Chaat',
    description: 'Crispy crackers topped with yogurt and chutneys',
    price: 50,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    available: true,
    preparationTime: 8,
    isVeg: true,
  },
  {
    id: '52',
    name: 'Dahi Puri',
    description: 'Hollow puris filled with yogurt and chutneys',
    price: 45,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    available: true,
    preparationTime: 8,
    isVeg: true,
  },
  {
    id: '53',
    name: 'Pani Puri',
    description: 'Crispy puris with spiced water and potato filling',
    price: 35,
    category: 'snacks',
    cuisine: 'snacks',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '54',
    name: 'Veg Momos',
    description: 'Steamed dumplings with vegetable filling',
    price: 60,
    category: 'snacks',
    cuisine: 'chinese',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400',
    available: true,
    preparationTime: 15,
    isVeg: true,
  },
  {
    id: '55',
    name: 'Chicken Momos',
    description: 'Steamed dumplings with spiced chicken filling',
    price: 80,
    category: 'snacks',
    cuisine: 'chinese',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400',
    available: true,
    preparationTime: 15,
    isVeg: false,
  },

  // Beverages (20+ items)
  {
    id: '56',
    name: 'Masala Chai',
    description: 'Indian spiced tea with milk',
    price: 15,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1597318147596-0a2e4b7a6c8d?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '57',
    name: 'Filter Coffee',
    description: 'South Indian style decoction coffee',
    price: 20,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '58',
    name: 'Lemon Tea',
    description: 'Refreshing tea with lemon and honey',
    price: 20,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1597318147596-0a2e4b7a6c8d?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '59',
    name: 'Green Tea',
    description: 'Healthy antioxidant-rich tea',
    price: 25,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1597318147596-0a2e4b7a6c8d?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '60',
    name: 'Black Coffee',
    description: 'Strong brewed coffee without milk',
    price: 25,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '61',
    name: 'Cappuccino',
    description: 'Espresso with steamed milk foam',
    price: 50,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400',
    available: true,
    preparationTime: 8,
    isVeg: true,
  },
  {
    id: '62',
    name: 'Latte',
    description: 'Espresso with steamed milk',
    price: 55,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400',
    available: true,
    preparationTime: 8,
    isVeg: true,
  },
  {
    id: '63',
    name: 'Cold Coffee',
    description: 'Chilled coffee with ice cream and milk',
    price: 60,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400',
    available: true,
    preparationTime: 8,
    isVeg: true,
  },
  {
    id: '64',
    name: 'Fresh Lime Soda',
    description: 'Refreshing lime juice with soda',
    price: 30,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1556881261-9d4a7a6a6b8b?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '65',
    name: 'Fresh Lime Water',
    description: 'Lime juice with water and mint',
    price: 25,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1556881261-9d4a7a6a6b8b?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '66',
    name: 'Mango Lassi',
    description: 'Yogurt-based mango drink',
    price: 50,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1600788907416-456578634209?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '67',
    name: 'Sweet Lassi',
    description: 'Sweetened yogurt drink',
    price: 40,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1600788907416-456578634209?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '68',
    name: 'Salt Lassi',
    description: 'Salted yogurt drink with spices',
    price: 40,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1600788907416-456578634209?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '69',
    name: 'Buttermilk',
    description: 'Spiced yogurt drink',
    price: 25,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1600788907416-456578634209?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '70',
    name: 'Watermelon Juice',
    description: 'Fresh watermelon juice',
    price: 45,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1546548970-71785318a17b?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '71',
    name: 'Orange Juice',
    description: 'Freshly squeezed orange juice',
    price: 50,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '72',
    name: 'Pineapple Juice',
    description: 'Fresh pineapple juice',
    price: 45,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1546548970-71785318a17b?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
  {
    id: '73',
    name: 'Mixed Fruit Juice',
    description: 'Blend of seasonal fruits',
    price: 55,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1546548970-71785318a17b?w=400',
    available: true,
    preparationTime: 8,
    isVeg: true,
  },
  {
    id: '74',
    name: 'Badam Milk',
    description: 'Almond-flavored milk drink',
    price: 50,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1600788907416-456578634209?w=400',
    available: true,
    preparationTime: 8,
    isVeg: true,
  },
  {
    id: '75',
    name: 'Rose Milk',
    description: 'Milk flavored with rose syrup',
    price: 45,
    category: 'beverages',
    cuisine: 'beverages',
    mealTime: 'all-day',
    image: 'https://images.unsplash.com/photo-1600788907416-456578634209?w=400',
    available: true,
    preparationTime: 5,
    isVeg: true,
  },
];

let orders: Order[] = [];
let users: User[] = [];
let notifications: Notification[] = [];

// Mock API functions
export const mockApi = {
  // Menu
  getMenuItems: async (): Promise<MenuItem[]> => {
    await new Promise(resolve => setTimeout(resolve, 500));
    return menuItems;
  },

  getMenuItem: async (id: string): Promise<MenuItem | undefined> => {
    await new Promise(resolve => setTimeout(resolve, 300));
    return menuItems.find(item => item.id === id);
  },

  // Auth
  login: async (email: string, password: string): Promise<User | null> => {
    await new Promise(resolve => setTimeout(resolve, 800));
    const user = users.find(u => u.email === email);
    return user || null;
  },

  register: async (name: string, email: string, password: string, role: 'customer' | 'staff'): Promise<User> => {
    await new Promise(resolve => setTimeout(resolve, 800));
    const newUser: User = {
      id: Date.now().toString(),
      name,
      email,
      role,
    };
    users.push(newUser);
    return newUser;
  },

  // Orders
  createOrder: async (userId: string, userName: string, items: CartItem[], totalAmount: number, paymentMethod: 'cash' | 'card' | 'upi'): Promise<Order> => {
    await new Promise(resolve => setTimeout(resolve, 1000));
    const newOrder: Order = {
      id: `ORD${Date.now()}`,
      userId,
      userName,
      items,
      totalAmount,
      status: 'pending',
      createdAt: new Date(),
      updatedAt: new Date(),
      paymentMethod,
    };
    orders.push(newOrder);
    
    // Create notification after order
    const notification: Notification = {
      id: `NOT${Date.now()}`,
      userId,
      title: 'Order Placed Successfully',
      message: `Your order #${newOrder.id} has been placed. We'll start preparing it soon!`,
      type: 'order',
      orderId: newOrder.id,
      read: false,
      createdAt: new Date(),
    };
    notifications.push(notification);
    
    // Simulate preparation notification after 30 seconds
    setTimeout(() => {
      const prepNotification: Notification = {
        id: `NOT${Date.now()}_prep`,
        userId,
        title: 'Order Being Prepared',
        message: `Your order #${newOrder.id} is now being prepared. It will take approximately ${newOrder.items.reduce((max, item) => Math.max(max, item.menuItem.preparationTime), 0)} minutes.`,
        type: 'status',
        orderId: newOrder.id,
        read: false,
        createdAt: new Date(),
      };
      notifications.push(prepNotification);
    }, 30000);
    
    return newOrder;
  },

  getOrders: async (userId?: string): Promise<Order[]> => {
    await new Promise(resolve => setTimeout(resolve, 500));
    if (userId) {
      return orders.filter(order => order.userId === userId).sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
    }
    return orders.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  },

  getOrder: async (orderId: string): Promise<Order | undefined> => {
    await new Promise(resolve => setTimeout(resolve, 300));
    return orders.find(order => order.id === orderId);
  },

  updateOrderStatus: async (orderId: string, status: OrderStatus, estimatedTime?: number, rejectionReason?: string): Promise<Order | undefined> => {
    await new Promise(resolve => setTimeout(resolve, 500));
    const order = orders.find(o => o.id === orderId);
    if (order) {
      order.status = status;
      order.updatedAt = new Date();
      if (estimatedTime) order.estimatedTime = estimatedTime;
      if (rejectionReason) order.rejectionReason = rejectionReason;
      
      // Create notification for status update
      const statusMessages = {
        approved: 'Your order has been approved and will be prepared soon.',
        preparing: 'Your order is being prepared now!',
        ready: 'Your order is ready for pickup!',
        completed: 'Your order has been completed. Thank you!',
        rejected: `Your order was rejected. ${rejectionReason || 'Please contact staff.'}`,
      };
      
      if (status !== 'pending') {
        const notification: Notification = {
          id: `NOT${Date.now()}_${status}`,
          userId: order.userId,
          title: `Order ${status.charAt(0).toUpperCase() + status.slice(1)}`,
          message: statusMessages[status] || `Order status updated to ${status}`,
          type: 'status',
          orderId: order.id,
          read: false,
          createdAt: new Date(),
        };
        notifications.push(notification);
      }
    }
    return order;
  },

  getPendingOrders: async (): Promise<Order[]> => {
    await new Promise(resolve => setTimeout(resolve, 500));
    return orders.filter(order => order.status === 'pending').sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime());
  },

  // Notifications
  getNotifications: async (userId: string): Promise<Notification[]> => {
    await new Promise(resolve => setTimeout(resolve, 300));
    return notifications
      .filter(n => n.userId === userId)
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  },

  markNotificationRead: async (notificationId: string): Promise<void> => {
    await new Promise(resolve => setTimeout(resolve, 200));
    const notification = notifications.find(n => n.id === notificationId);
    if (notification) {
      notification.read = true;
    }
  },

  markAllNotificationsRead: async (userId: string): Promise<void> => {
    await new Promise(resolve => setTimeout(resolve, 300));
    notifications.forEach(n => {
      if (n.userId === userId) {
        n.read = true;
      }
    });
  },
};